Nolio fork pull request
GoldenCheetah/GoldenCheetah pull request #4169
Opened 2022-02-14 08:09 UTC by Thomas-Plazas

2022-02-14 09:12 UTC, liversedge commented on src/Cloud/OAuthDialog.cpp
> +#include <QDebug>
please remove

2022-02-14 09:13 UTC, liversedge commented on src/Cloud/OAuthDialog.cpp
> +            urlstr = QString("https://www.dropbox.com/oauth2/authorize?");
there is new whitespace in here and the next few lines to remove.

2022-02-14 09:14 UTC, liversedge commented on src/Cloud/OAuthDialog.cpp
> +    bool is_nolio = site == NOLIO;
is_nolio does not appear to be used and isn't adding much value anyway, please remove

2022-02-14 09:14 UTC, liversedge commented on src/Cloud/OAuthDialog.cpp
> +            qDebug() << "error  111";
developer debug should be removed

2022-02-14 09:30 UTC, liversedge commented on src/src.pro
these should now be added to the proper lines in src.pro (around L615)

2022-02-14 09:32 UTC, liversedge commented
I have added some basic code comments, but have not tested the change.
The commit requires rebasing to squash and merge commits (see: git rebase --i) 

@grauser is testing this and will likely feedback if there are any defects etc

2022-02-14 09:39 UTC, liversedge commented
Please also remove the .idea folder from the commit.

2022-02-14 09:41 UTC, liversedge commented on src/Cloud/Nolio.cpp
> +            if (sport_id == 14 or sport_id == 15 or sport_id == 18 or sport_id == 28 or sport_id == 35 or sport_id == 36) ride->setTag("Sport", "Bike");
or is not a valid keyword in C++ use || this breaks on windows builds, it is repeated for multiple lines.

2022-02-17 21:36 UTC, grauser requested changes
I tested the PR and made some suggestions in Nolio.cpp and Nolio.h

2022-02-18 12:33 UTC, grauser approved these changes

2022-02-18 13:20 UTC, merged

2022-02-18 13:21 UTC, liversedge commented
Thanks Thomas, and thanks Damien for the review!